// Code generated by MockGen. DO NOT EDIT.
// Source: events.go
//
// Generated by this command:
//
//	mockgen -destination=mock/events.mock.go -package=mock -source events.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	api "github.com/qubic/archive-query-service/v2/api/archive-query-service/v2"
	entities "github.com/qubic/archive-query-service/v2/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockEventsRepository is a mock of EventsRepository interface.
type MockEventsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEventsRepositoryMockRecorder
	isgomock struct{}
}

// MockEventsRepositoryMockRecorder is the mock recorder for MockEventsRepository.
type MockEventsRepositoryMockRecorder struct {
	mock *MockEventsRepository
}

// NewMockEventsRepository creates a new mock instance.
func NewMockEventsRepository(ctrl *gomock.Controller) *MockEventsRepository {
	mock := &MockEventsRepository{ctrl: ctrl}
	mock.recorder = &MockEventsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventsRepository) EXPECT() *MockEventsRepositoryMockRecorder {
	return m.recorder
}

// GetEvents mocks base method.
func (m *MockEventsRepository) GetEvents(ctx context.Context, filters map[string][]string, from, size uint32) ([]*api.Event, *entities.Hits, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvents", ctx, filters, from, size)
	ret0, _ := ret[0].([]*api.Event)
	ret1, _ := ret[1].(*entities.Hits)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetEvents indicates an expected call of GetEvents.
func (mr *MockEventsRepositoryMockRecorder) GetEvents(ctx, filters, from, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvents", reflect.TypeOf((*MockEventsRepository)(nil).GetEvents), ctx, filters, from, size)
}
