### Get transactions for one identity

POST {{host}}/getTransactionsForIdentity
Accept: application/json

{
    "identity": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB",
    "filters": {
           "inputType": "0"
    },
    "ranges": {
        "amount": {
            "gt": "1000000"
        },
        "tickNumber": {
            "gte": "25563104"
        }
    },
    "pagination": {
      "size": 3
    }
}

### Get transaction

POST {{host}}/getTransactionByHash
Accept: application/json

{
    "hash": "wnkujtaavborugjhgudeimborfpgyudnuekalkbsjeaxiejvvdgahdrerajo"
}

###