### Get transactions for one identity

POST {{host}}/getTransactionsForIdentity
Accept: application/json

{
    "identity": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB",
    "filters": {
           "inputType": "0",
           "source-exclude": "AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ, HOPUKLUXCKGDDEBSYRRPJTSFYEKBTDYCJSVZJLEIZEBJCDLAVOCMKMTBTDLB"
    },
    "ranges": {
        "amount": {
            "gt": "1000"
        },
        "tickNumber": {
            "lte": "25563000"
        }
    },
    "pagination": {
      "size": 10
    }
}

### Get tickData

POST {{host}}/getTickData
Accept: application/json

{
    "tickNumber": 28361691
}

### Get transaction

POST {{host}}/getTransactionByHash
Accept: application/json

{
    "hash": "wnkujtaavborugjhgudeimborfpgyudnuekalkbsjeaxiejvvdgahdrerajo"
}

###