// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: messages.proto

package api

import (
	_ "github.com/google/gnostic/openapiv3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LastProcessedTick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TickNumber    uint32                 `protobuf:"varint,1,opt,name=tick_number,json=tickNumber,proto3" json:"tick_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastProcessedTick) Reset() {
	*x = LastProcessedTick{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastProcessedTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastProcessedTick) ProtoMessage() {}

func (x *LastProcessedTick) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastProcessedTick.ProtoReflect.Descriptor instead.
func (*LastProcessedTick) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *LastProcessedTick) GetTickNumber() uint32 {
	if x != nil {
		return x.TickNumber
	}
	return 0
}

type NextAvailableTick struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NextTickNumber uint32                 `protobuf:"varint,1,opt,name=next_tick_number,json=nextTickNumber,proto3" json:"next_tick_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NextAvailableTick) Reset() {
	*x = NextAvailableTick{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextAvailableTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextAvailableTick) ProtoMessage() {}

func (x *NextAvailableTick) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextAvailableTick.ProtoReflect.Descriptor instead.
func (*NextAvailableTick) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *NextAvailableTick) GetNextTickNumber() uint32 {
	if x != nil {
		return x.NextTickNumber
	}
	return 0
}

// Transaction
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	TickNumber    uint32                 `protobuf:"varint,5,opt,name=tick_number,json=tickNumber,proto3" json:"tick_number,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	InputType     uint32                 `protobuf:"varint,7,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	InputSize     uint32                 `protobuf:"varint,8,opt,name=input_size,json=inputSize,proto3" json:"input_size,omitempty"`
	InputData     string                 `protobuf:"bytes,9,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
	Signature     string                 `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	MoneyFlew     bool                   `protobuf:"varint,11,opt,name=money_flew,json=moneyFlew,proto3" json:"money_flew,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Transaction) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Transaction) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Transaction) GetTickNumber() uint32 {
	if x != nil {
		return x.TickNumber
	}
	return 0
}

func (x *Transaction) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Transaction) GetInputType() uint32 {
	if x != nil {
		return x.InputType
	}
	return 0
}

func (x *Transaction) GetInputSize() uint32 {
	if x != nil {
		return x.InputSize
	}
	return 0
}

func (x *Transaction) GetInputData() string {
	if x != nil {
		return x.InputData
	}
	return ""
}

func (x *Transaction) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Transaction) GetMoneyFlew() bool {
	if x != nil {
		return x.MoneyFlew
	}
	return false
}

// TickData
type TickData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TickNumber        uint32                 `protobuf:"varint,1,opt,name=tick_number,json=tickNumber,proto3" json:"tick_number,omitempty"`
	Epoch             uint32                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ComputorIndex     uint32                 `protobuf:"varint,3,opt,name=computor_index,json=computorIndex,proto3" json:"computor_index,omitempty"`
	Timestamp         uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	VarStruct         string                 `protobuf:"bytes,5,opt,name=var_struct,json=varStruct,proto3" json:"var_struct,omitempty"`
	TimeLock          string                 `protobuf:"bytes,6,opt,name=time_lock,json=timeLock,proto3" json:"time_lock,omitempty"`
	TransactionHashes []string               `protobuf:"bytes,7,rep,name=transaction_hashes,json=transactionHashes,proto3" json:"transaction_hashes,omitempty"`
	ContractFees      []int64                `protobuf:"varint,8,rep,packed,name=contract_fees,json=contractFees,proto3" json:"contract_fees,omitempty"`
	Signature         string                 `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TickData) Reset() {
	*x = TickData{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickData) ProtoMessage() {}

func (x *TickData) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickData.ProtoReflect.Descriptor instead.
func (*TickData) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *TickData) GetTickNumber() uint32 {
	if x != nil {
		return x.TickNumber
	}
	return 0
}

func (x *TickData) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TickData) GetComputorIndex() uint32 {
	if x != nil {
		return x.ComputorIndex
	}
	return 0
}

func (x *TickData) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TickData) GetVarStruct() string {
	if x != nil {
		return x.VarStruct
	}
	return ""
}

func (x *TickData) GetTimeLock() string {
	if x != nil {
		return x.TimeLock
	}
	return ""
}

func (x *TickData) GetTransactionHashes() []string {
	if x != nil {
		return x.TransactionHashes
	}
	return nil
}

func (x *TickData) GetContractFees() []int64 {
	if x != nil {
		return x.ContractFees
	}
	return nil
}

func (x *TickData) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// ProcessedTickInterval
type ProcessedTickInterval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint32                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	FirstTick     uint32                 `protobuf:"varint,2,opt,name=first_tick,json=firstTick,proto3" json:"first_tick,omitempty"`
	LastTick      uint32                 `protobuf:"varint,3,opt,name=last_tick,json=lastTick,proto3" json:"last_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessedTickInterval) Reset() {
	*x = ProcessedTickInterval{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedTickInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedTickInterval) ProtoMessage() {}

func (x *ProcessedTickInterval) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedTickInterval.ProtoReflect.Descriptor instead.
func (*ProcessedTickInterval) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessedTickInterval) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ProcessedTickInterval) GetFirstTick() uint32 {
	if x != nil {
		return x.FirstTick
	}
	return 0
}

func (x *ProcessedTickInterval) GetLastTick() uint32 {
	if x != nil {
		return x.LastTick
	}
	return 0
}

// Pagination
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint32                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *Pagination) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Pagination) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// GetTransactionByHashRequest
type GetTransactionByHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionByHashRequest) Reset() {
	*x = GetTransactionByHashRequest{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionByHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionByHashRequest) ProtoMessage() {}

func (x *GetTransactionByHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionByHashRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionByHashRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransactionByHashRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// GetTransactionByHashResponse
type GetTransactionByHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionByHashResponse) Reset() {
	*x = GetTransactionByHashResponse{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionByHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionByHashResponse) ProtoMessage() {}

func (x *GetTransactionByHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionByHashResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionByHashResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransactionByHashResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// GetTransactionsForTickRequest
type GetTransactionsForTickRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the tick number to get the transactions for.
	TickNumber    uint32 `protobuf:"varint,1,opt,name=tick_number,json=tickNumber,proto3" json:"tick_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsForTickRequest) Reset() {
	*x = GetTransactionsForTickRequest{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsForTickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsForTickRequest) ProtoMessage() {}

func (x *GetTransactionsForTickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsForTickRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsForTickRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *GetTransactionsForTickRequest) GetTickNumber() uint32 {
	if x != nil {
		return x.TickNumber
	}
	return 0
}

// GetTransactionsForTickResponse
type GetTransactionsForTickResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsForTickResponse) Reset() {
	*x = GetTransactionsForTickResponse{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsForTickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsForTickResponse) ProtoMessage() {}

func (x *GetTransactionsForTickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsForTickResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsForTickResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *GetTransactionsForTickResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// Range
type Range struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to LowerBound:
	//
	//	*Range_Gt
	//	*Range_Gte
	LowerBound isRange_LowerBound `protobuf_oneof:"lower_bound"`
	// Types that are valid to be assigned to UpperBound:
	//
	//	*Range_Lt
	//	*Range_Lte
	UpperBound    isRange_UpperBound `protobuf_oneof:"upper_bound"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Range) Reset() {
	*x = Range{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *Range) GetLowerBound() isRange_LowerBound {
	if x != nil {
		return x.LowerBound
	}
	return nil
}

func (x *Range) GetGt() string {
	if x != nil {
		if x, ok := x.LowerBound.(*Range_Gt); ok {
			return x.Gt
		}
	}
	return ""
}

func (x *Range) GetGte() string {
	if x != nil {
		if x, ok := x.LowerBound.(*Range_Gte); ok {
			return x.Gte
		}
	}
	return ""
}

func (x *Range) GetUpperBound() isRange_UpperBound {
	if x != nil {
		return x.UpperBound
	}
	return nil
}

func (x *Range) GetLt() string {
	if x != nil {
		if x, ok := x.UpperBound.(*Range_Lt); ok {
			return x.Lt
		}
	}
	return ""
}

func (x *Range) GetLte() string {
	if x != nil {
		if x, ok := x.UpperBound.(*Range_Lte); ok {
			return x.Lte
		}
	}
	return ""
}

type isRange_LowerBound interface {
	isRange_LowerBound()
}

type Range_Gt struct {
	Gt string `protobuf:"bytes,1,opt,name=gt,proto3,oneof"`
}

type Range_Gte struct {
	Gte string `protobuf:"bytes,2,opt,name=gte,proto3,oneof"`
}

func (*Range_Gt) isRange_LowerBound() {}

func (*Range_Gte) isRange_LowerBound() {}

type isRange_UpperBound interface {
	isRange_UpperBound()
}

type Range_Lt struct {
	Lt string `protobuf:"bytes,3,opt,name=lt,proto3,oneof"`
}

type Range_Lte struct {
	Lte string `protobuf:"bytes,4,opt,name=lte,proto3,oneof"`
}

func (*Range_Lt) isRange_UpperBound() {}

func (*Range_Lte) isRange_UpperBound() {}

// GetTransactionsForIdentityRequest
type GetTransactionsForIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ranges        map[string]*Range      `protobuf:"bytes,3,rep,name=ranges,proto3" json:"ranges,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Pagination    *Pagination            `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsForIdentityRequest) Reset() {
	*x = GetTransactionsForIdentityRequest{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsForIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsForIdentityRequest) ProtoMessage() {}

func (x *GetTransactionsForIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsForIdentityRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsForIdentityRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *GetTransactionsForIdentityRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *GetTransactionsForIdentityRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *GetTransactionsForIdentityRequest) GetRanges() map[string]*Range {
	if x != nil {
		return x.Ranges
	}
	return nil
}

func (x *GetTransactionsForIdentityRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Hits
type Hits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint32                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	From          uint32                 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hits) Reset() {
	*x = Hits{}
	mi := &file_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hits) ProtoMessage() {}

func (x *Hits) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hits.ProtoReflect.Descriptor instead.
func (*Hits) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *Hits) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Hits) GetFrom() uint32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Hits) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// GetTransactionsForIdentityResponse
type GetTransactionsForIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValidForTick  uint32                 `protobuf:"varint,1,opt,name=valid_for_tick,json=validForTick,proto3" json:"valid_for_tick,omitempty"`
	Hits          *Hits                  `protobuf:"bytes,2,opt,name=hits,proto3" json:"hits,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsForIdentityResponse) Reset() {
	*x = GetTransactionsForIdentityResponse{}
	mi := &file_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsForIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsForIdentityResponse) ProtoMessage() {}

func (x *GetTransactionsForIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsForIdentityResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsForIdentityResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

func (x *GetTransactionsForIdentityResponse) GetValidForTick() uint32 {
	if x != nil {
		return x.ValidForTick
	}
	return 0
}

func (x *GetTransactionsForIdentityResponse) GetHits() *Hits {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *GetTransactionsForIdentityResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// GetTickDataRequest
type GetTickDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TickNumber    uint32                 `protobuf:"varint,1,opt,name=tick_number,json=tickNumber,proto3" json:"tick_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickDataRequest) Reset() {
	*x = GetTickDataRequest{}
	mi := &file_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickDataRequest) ProtoMessage() {}

func (x *GetTickDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickDataRequest.ProtoReflect.Descriptor instead.
func (*GetTickDataRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14}
}

func (x *GetTickDataRequest) GetTickNumber() uint32 {
	if x != nil {
		return x.TickNumber
	}
	return 0
}

// GetTickDataResponse
type GetTickDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TickData      *TickData              `protobuf:"bytes,1,opt,name=tick_data,json=tickData,proto3" json:"tick_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickDataResponse) Reset() {
	*x = GetTickDataResponse{}
	mi := &file_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickDataResponse) ProtoMessage() {}

func (x *GetTickDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickDataResponse.ProtoReflect.Descriptor instead.
func (*GetTickDataResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{15}
}

func (x *GetTickDataResponse) GetTickData() *TickData {
	if x != nil {
		return x.TickData
	}
	return nil
}

// GetProcessedTickIntervalsResponse
type GetProcessedTickIntervalsResponse struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	ProcessedTickIntervals []*ProcessedTickInterval `protobuf:"bytes,1,rep,name=processed_tick_intervals,json=processedTickIntervals,proto3" json:"processed_tick_intervals,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetProcessedTickIntervalsResponse) Reset() {
	*x = GetProcessedTickIntervalsResponse{}
	mi := &file_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessedTickIntervalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessedTickIntervalsResponse) ProtoMessage() {}

func (x *GetProcessedTickIntervalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessedTickIntervalsResponse.ProtoReflect.Descriptor instead.
func (*GetProcessedTickIntervalsResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{16}
}

func (x *GetProcessedTickIntervalsResponse) GetProcessedTickIntervals() []*ProcessedTickInterval {
	if x != nil {
		return x.ProcessedTickIntervals
	}
	return nil
}

// GetLastProcessedTickResponse
type GetLastProcessedTickResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TickNumber          uint32                 `protobuf:"varint,1,opt,name=tick_number,json=tickNumber,proto3" json:"tick_number,omitempty"`
	Epoch               uint32                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	IntervalInitialTick uint32                 `protobuf:"varint,3,opt,name=interval_initial_tick,json=intervalInitialTick,proto3" json:"interval_initial_tick,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetLastProcessedTickResponse) Reset() {
	*x = GetLastProcessedTickResponse{}
	mi := &file_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastProcessedTickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastProcessedTickResponse) ProtoMessage() {}

func (x *GetLastProcessedTickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastProcessedTickResponse.ProtoReflect.Descriptor instead.
func (*GetLastProcessedTickResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{17}
}

func (x *GetLastProcessedTickResponse) GetTickNumber() uint32 {
	if x != nil {
		return x.TickNumber
	}
	return 0
}

func (x *GetLastProcessedTickResponse) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *GetLastProcessedTickResponse) GetIntervalInitialTick() uint32 {
	if x != nil {
		return x.IntervalInitialTick
	}
	return 0
}

// GetComputorListsForEpochRequest
type GetComputorListsForEpochRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint32                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetComputorListsForEpochRequest) Reset() {
	*x = GetComputorListsForEpochRequest{}
	mi := &file_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetComputorListsForEpochRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetComputorListsForEpochRequest) ProtoMessage() {}

func (x *GetComputorListsForEpochRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetComputorListsForEpochRequest.ProtoReflect.Descriptor instead.
func (*GetComputorListsForEpochRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{18}
}

func (x *GetComputorListsForEpochRequest) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

// ComputorList
type ComputorList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint32                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	TickNumber    uint32                 `protobuf:"varint,2,opt,name=tick_number,json=tickNumber,proto3" json:"tick_number,omitempty"`
	Identities    []string               `protobuf:"bytes,3,rep,name=identities,proto3" json:"identities,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputorList) Reset() {
	*x = ComputorList{}
	mi := &file_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputorList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputorList) ProtoMessage() {}

func (x *ComputorList) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputorList.ProtoReflect.Descriptor instead.
func (*ComputorList) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{19}
}

func (x *ComputorList) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ComputorList) GetTickNumber() uint32 {
	if x != nil {
		return x.TickNumber
	}
	return 0
}

func (x *ComputorList) GetIdentities() []string {
	if x != nil {
		return x.Identities
	}
	return nil
}

func (x *ComputorList) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// GetComputorListsForEpochResponse
type GetComputorListsForEpochResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ComputorsLists []*ComputorList        `protobuf:"bytes,1,rep,name=computors_lists,json=computorsLists,proto3" json:"computors_lists,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetComputorListsForEpochResponse) Reset() {
	*x = GetComputorListsForEpochResponse{}
	mi := &file_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetComputorListsForEpochResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetComputorListsForEpochResponse) ProtoMessage() {}

func (x *GetComputorListsForEpochResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetComputorListsForEpochResponse.ProtoReflect.Descriptor instead.
func (*GetComputorListsForEpochResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{20}
}

func (x *GetComputorListsForEpochResponse) GetComputorsLists() []*ComputorList {
	if x != nil {
		return x.ComputorsLists
	}
	return nil
}

// HealthResponse
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{21}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\x13qubic.v2.archive.pb\x1a\x1bopenapiv3/annotations.proto\"4\n" +
	"\x11LastProcessedTick\x12\x1f\n" +
	"\vtick_number\x18\x01 \x01(\rR\n" +
	"tickNumber\"=\n" +
	"\x11NextAvailableTick\x12(\n" +
	"\x10next_tick_number\x18\x01 \x01(\rR\x0enextTickNumber\"\xda\x05\n" +
	"\vTransaction\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\x12\x1f\n" +
	"\vtick_number\x18\x05 \x01(\rR\n" +
	"tickNumber\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\x12\x8b\x01\n" +
	"\n" +
	"input_type\x18\a \x01(\rBl\xbaGi\x92\x02fSmart contract procedure index. (The smart contract procedure this transaction is supposed to trigger)R\tinputType\x12C\n" +
	"\n" +
	"input_size\x18\b \x01(\rB$\xbaG!\x92\x02\x1eSize of input_data byte array.R\tinputSize\x12c\n" +
	"\n" +
	"input_data\x18\t \x01(\tBD\xbaGA\x92\x02>Base64 encoded byte array containing a smart contract payload.R\tinputData\x12h\n" +
	"\tsignature\x18\n" +
	" \x01(\tBJ\xbaGG\x92\x02DBase64 encoded byte array representing the transactions's signature.R\tsignature\x12\x83\x01\n" +
	"\n" +
	"money_flew\x18\v \x01(\bBd\xbaGa\x92\x02^Money flew is an additional information provided by some nodes with the tx status addon patch.R\tmoneyFlew\"\xb4\x02\n" +
	"\bTickData\x12\x1f\n" +
	"\vtick_number\x18\x01 \x01(\rR\n" +
	"tickNumber\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\rR\x05epoch\x12%\n" +
	"\x0ecomputor_index\x18\x03 \x01(\rR\rcomputorIndex\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12\x1d\n" +
	"\n" +
	"var_struct\x18\x05 \x01(\tR\tvarStruct\x12\x1b\n" +
	"\ttime_lock\x18\x06 \x01(\tR\btimeLock\x12-\n" +
	"\x12transaction_hashes\x18\a \x03(\tR\x11transactionHashes\x12#\n" +
	"\rcontract_fees\x18\b \x03(\x03R\fcontractFees\x12\x1c\n" +
	"\tsignature\x18\t \x01(\tR\tsignature\"\xf1\x01\n" +
	"\x15ProcessedTickInterval\x129\n" +
	"\x05epoch\x18\x01 \x01(\rB#\xbaG \x92\x02\x1dThe epoch the interval is in.R\x05epoch\x12P\n" +
	"\n" +
	"first_tick\x18\x02 \x01(\rB1\xbaG.\x92\x02+The initial processed tick of the interval.R\tfirstTick\x12K\n" +
	"\tlast_tick\x18\x03 \x01(\rB.\xbaG+\x92\x02(The last processed tick of the interval.R\blastTick\"\xa8\x02\n" +
	"\n" +
	"Pagination\x12m\n" +
	"\x06offset\x18\x01 \x01(\rBU\xbaGR\x92\x02OThe offset specifies the starting point of the returned data. Defaults to zero.R\x06offset\x12a\n" +
	"\x04size\x18\x02 \x01(\rBM\xbaGJ\x92\x02GThe size specifies how many results should be returned. Defaults to 10.R\x04size:H\xbaGE\x92\x02BThe number of maximum results (offset + size) is limited to 10000.\"U\n" +
	"\x1bGetTransactionByHashRequest\x126\n" +
	"\x04hash\x18\x01 \x01(\tB\"\xbaG\x1f\x92\x02\x1cThe hash of the transaction.R\x04hash\"\x91\x01\n" +
	"\x1cGetTransactionByHashResponse\x12q\n" +
	"\vtransaction\x18\x01 \x01(\v2 .qubic.v2.archive.pb.TransactionB-\xbaG*\x92\x02'The transaction for the requested hash.R\vtransaction\"t\n" +
	"\x1dGetTransactionsForTickRequest\x12S\n" +
	"\vtick_number\x18\x01 \x01(\rB2\xbaG/\x92\x02,The tick number to get the transactions for.R\n" +
	"tickNumber\"\x9d\x01\n" +
	"\x1eGetTransactionsForTickResponse\x12{\n" +
	"\ftransactions\x18\x01 \x03(\v2 .qubic.v2.archive.pb.TransactionB5\xbaG2\x92\x02/The transactions for the requested tick number.R\ftransactions\"\xd1\x01\n" +
	"\x05Range\x12%\n" +
	"\x02gt\x18\x01 \x01(\tB\x13\xbaG\x10\x92\x02\rGreater than.H\x00R\x02gt\x120\n" +
	"\x03gte\x18\x02 \x01(\tB\x1c\xbaG\x19\x92\x02\x16Greater than or equal.H\x00R\x03gte\x12\"\n" +
	"\x02lt\x18\x03 \x01(\tB\x10\xbaG\r\x92\x02\n" +
	"Less than.H\x01R\x02lt\x12-\n" +
	"\x03lte\x18\x04 \x01(\tB\x19\xbaG\x16\x92\x02\x13Less than or equal.H\x01R\x03lteB\r\n" +
	"\vlower_boundB\r\n" +
	"\vupper_bound\"\xdf\a\n" +
	"!GetTransactionsForIdentityRequest\x12\x86\x01\n" +
	"\bidentity\x18\x01 \x01(\tBj\xbaGg\x92\x02dThe identity to get the transactions for. Incoming and outgoing transactions are queried by default.R\bidentity\x12\x93\x01\n" +
	"\afilters\x18\x02 \x03(\v2C.qubic.v2.archive.pb.GetTransactionsForIdentityRequest.FiltersEntryB4\xbaG1\x92\x02.Filters restrict the results by single values.R\afilters\x12\x9d\x01\n" +
	"\x06ranges\x18\x03 \x03(\v2B.qubic.v2.archive.pb.GetTransactionsForIdentityRequest.RangesEntryBA\xbaG>\x92\x02;Ranges restrict the results by a maximum and minimum value.R\x06ranges\x12d\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x1f.qubic.v2.archive.pb.PaginationB#\xbaG \x92\x02\x1dOptional paging information .R\n" +
	"pagination\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aU\n" +
	"\vRangesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.qubic.v2.archive.pb.RangeR\x05value:\x028\x01:\x81\x02\xbaG\xfd\x01:\xfa\x01\x12\xf7\x01identity: AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ\n" +
	"filters:\n" +
	"  destination: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB\n" +
	"  inputType: \"0\"\n" +
	"ranges:\n" +
	"  amount:\n" +
	"    gte: \"1000000000\"\n" +
	"pagination:\n" +
	"  offset: 0\n" +
	"  size: 10\"\x9f\x02\n" +
	"\x04Hits\x12_\n" +
	"\x05total\x18\x01 \x01(\rBI\xbaGF\x92\x02CThe total number of hits available in the archive. Capped at 10000.R\x05total\x12I\n" +
	"\x04from\x18\x02 \x01(\rB5\xbaG2\x92\x02/Starting offset of the hits that were returned.R\x04from\x122\n" +
	"\x04size\x18\x03 \x01(\rB\x1e\xbaG\x1b\x92\x02\x18Number of returned hits.R\x04size:7\xbaG4\x92\x021Provides information about the number of results.\"\xe0\x02\n" +
	"\"GetTransactionsForIdentityResponse\x12W\n" +
	"\x0evalid_for_tick\x18\x01 \x01(\rB1\xbaG.\x92\x02+The response is valid for this tick number.R\fvalidForTick\x12\\\n" +
	"\x04hits\x18\x02 \x01(\v2\x19.qubic.v2.archive.pb.HitsB-\xbaG*\x92\x02'Information about the returned results.R\x04hits\x12\x82\x01\n" +
	"\ftransactions\x18\x03 \x03(\v2 .qubic.v2.archive.pb.TransactionB<\xbaG9\x92\x026List of transactions that matched the search criteria.R\ftransactions\"o\n" +
	"\x12GetTickDataRequest\x12Y\n" +
	"\vtick_number\x18\x01 \x01(\rB8\xbaG5\x92\x022The number of tick the tick data is requested for.R\n" +
	"tickNumber\"}\n" +
	"\x13GetTickDataResponse\x12f\n" +
	"\ttick_data\x18\x01 \x01(\v2\x1d.qubic.v2.archive.pb.TickDataB*\xbaG'\x92\x02$The tick data of the requested tick.R\btickData\"\xbf\x01\n" +
	"!GetProcessedTickIntervalsResponse\x12\x99\x01\n" +
	"\x18processed_tick_intervals\x18\x01 \x03(\v2*.qubic.v2.archive.pb.ProcessedTickIntervalB3\xbaG0\x92\x02-A list of tick intervals that were processed.R\x16processedTickIntervals\"\xb0\x02\n" +
	"\x1cGetLastProcessedTickResponse\x12`\n" +
	"\vtick_number\x18\x01 \x01(\rB?\xbaG<\x92\x029The last processed tick that is available in the archive.R\n" +
	"tickNumber\x12D\n" +
	"\x05epoch\x18\x02 \x01(\rB.\xbaG+\x92\x02(The epoch the last processed tick is in.R\x05epoch\x12h\n" +
	"\x15interval_initial_tick\x18\x03 \x01(\rB4\xbaG1\x92\x02.The initial tick of the current tick interval.R\x13intervalInitialTick\"n\n" +
	"\x1fGetComputorListsForEpochRequest\x12K\n" +
	"\x05epoch\x18\x01 \x01(\rB5\xbaG2\x92\x02/The epoch number to get the computor lists for.R\x05epoch\"\xcc\x02\n" +
	"\fComputorList\x12)\n" +
	"\x05epoch\x18\x01 \x01(\rB\x13\xbaG\x10\x92\x02\rEpoch number.R\x05epoch\x12t\n" +
	"\vtick_number\x18\x02 \x01(\rBS\xbaGP\x92\x02MTick number when the list was received by the archive after it was published.R\n" +
	"tickNumber\x12Y\n" +
	"\n" +
	"identities\x18\x03 \x03(\tB9\xbaG6\x92\x023List of computor identities (signed by arbitrator).R\n" +
	"identities\x12@\n" +
	"\tsignature\x18\x04 \x01(\tB\"\xbaG\x1f\x92\x02\x1cSignature of the arbitrator.R\tsignature\"\xa7\x01\n" +
	" GetComputorListsForEpochResponse\x12\x82\x01\n" +
	"\x0fcomputors_lists\x18\x01 \x03(\v2!.qubic.v2.archive.pb.ComputorListB6\xbaG3\x92\x020The lists of computors that voted in this epoch.R\x0ecomputorsLists\"J\n" +
	"\x0eHealthResponse\x128\n" +
	"\x06status\x18\x01 \x01(\tB \xbaG\x1d\x92\x02\x1aHealth status information.R\x06statusB,Z*github.com/qubic/archive-query-service/apib\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_messages_proto_goTypes = []any{
	(*LastProcessedTick)(nil),                  // 0: qubic.v2.archive.pb.LastProcessedTick
	(*NextAvailableTick)(nil),                  // 1: qubic.v2.archive.pb.NextAvailableTick
	(*Transaction)(nil),                        // 2: qubic.v2.archive.pb.Transaction
	(*TickData)(nil),                           // 3: qubic.v2.archive.pb.TickData
	(*ProcessedTickInterval)(nil),              // 4: qubic.v2.archive.pb.ProcessedTickInterval
	(*Pagination)(nil),                         // 5: qubic.v2.archive.pb.Pagination
	(*GetTransactionByHashRequest)(nil),        // 6: qubic.v2.archive.pb.GetTransactionByHashRequest
	(*GetTransactionByHashResponse)(nil),       // 7: qubic.v2.archive.pb.GetTransactionByHashResponse
	(*GetTransactionsForTickRequest)(nil),      // 8: qubic.v2.archive.pb.GetTransactionsForTickRequest
	(*GetTransactionsForTickResponse)(nil),     // 9: qubic.v2.archive.pb.GetTransactionsForTickResponse
	(*Range)(nil),                              // 10: qubic.v2.archive.pb.Range
	(*GetTransactionsForIdentityRequest)(nil),  // 11: qubic.v2.archive.pb.GetTransactionsForIdentityRequest
	(*Hits)(nil),                               // 12: qubic.v2.archive.pb.Hits
	(*GetTransactionsForIdentityResponse)(nil), // 13: qubic.v2.archive.pb.GetTransactionsForIdentityResponse
	(*GetTickDataRequest)(nil),                 // 14: qubic.v2.archive.pb.GetTickDataRequest
	(*GetTickDataResponse)(nil),                // 15: qubic.v2.archive.pb.GetTickDataResponse
	(*GetProcessedTickIntervalsResponse)(nil),  // 16: qubic.v2.archive.pb.GetProcessedTickIntervalsResponse
	(*GetLastProcessedTickResponse)(nil),       // 17: qubic.v2.archive.pb.GetLastProcessedTickResponse
	(*GetComputorListsForEpochRequest)(nil),    // 18: qubic.v2.archive.pb.GetComputorListsForEpochRequest
	(*ComputorList)(nil),                       // 19: qubic.v2.archive.pb.ComputorList
	(*GetComputorListsForEpochResponse)(nil),   // 20: qubic.v2.archive.pb.GetComputorListsForEpochResponse
	(*HealthResponse)(nil),                     // 21: qubic.v2.archive.pb.HealthResponse
	nil,                                        // 22: qubic.v2.archive.pb.GetTransactionsForIdentityRequest.FiltersEntry
	nil,                                        // 23: qubic.v2.archive.pb.GetTransactionsForIdentityRequest.RangesEntry
}
var file_messages_proto_depIdxs = []int32{
	2,  // 0: qubic.v2.archive.pb.GetTransactionByHashResponse.transaction:type_name -> qubic.v2.archive.pb.Transaction
	2,  // 1: qubic.v2.archive.pb.GetTransactionsForTickResponse.transactions:type_name -> qubic.v2.archive.pb.Transaction
	22, // 2: qubic.v2.archive.pb.GetTransactionsForIdentityRequest.filters:type_name -> qubic.v2.archive.pb.GetTransactionsForIdentityRequest.FiltersEntry
	23, // 3: qubic.v2.archive.pb.GetTransactionsForIdentityRequest.ranges:type_name -> qubic.v2.archive.pb.GetTransactionsForIdentityRequest.RangesEntry
	5,  // 4: qubic.v2.archive.pb.GetTransactionsForIdentityRequest.pagination:type_name -> qubic.v2.archive.pb.Pagination
	12, // 5: qubic.v2.archive.pb.GetTransactionsForIdentityResponse.hits:type_name -> qubic.v2.archive.pb.Hits
	2,  // 6: qubic.v2.archive.pb.GetTransactionsForIdentityResponse.transactions:type_name -> qubic.v2.archive.pb.Transaction
	3,  // 7: qubic.v2.archive.pb.GetTickDataResponse.tick_data:type_name -> qubic.v2.archive.pb.TickData
	4,  // 8: qubic.v2.archive.pb.GetProcessedTickIntervalsResponse.processed_tick_intervals:type_name -> qubic.v2.archive.pb.ProcessedTickInterval
	19, // 9: qubic.v2.archive.pb.GetComputorListsForEpochResponse.computors_lists:type_name -> qubic.v2.archive.pb.ComputorList
	10, // 10: qubic.v2.archive.pb.GetTransactionsForIdentityRequest.RangesEntry.value:type_name -> qubic.v2.archive.pb.Range
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[10].OneofWrappers = []any{
		(*Range_Gt)(nil),
		(*Range_Gte)(nil),
		(*Range_Lt)(nil),
		(*Range_Lte)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
