// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.23.4
// source: query_services.proto

package api

import (
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_query_services_proto protoreflect.FileDescriptor

const file_query_services_proto_rawDesc = "" +
	"\n" +
	"\x14query_services.proto\x12\x13qubic.v2.archive.pb\x1a\x0emessages.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1bopenapiv3/annotations.proto2\xfd\x0e\n" +
	"\x13ArchiveQueryService\x12\xfb\x01\n" +
	"\x14GetTransactionByHash\x120.qubic.v2.archive.pb.GetTransactionByHashRequest\x1a1.qubic.v2.archive.pb.GetTransactionByHashResponse\"~\xbaGN\n" +
	"\fTransactions\x12\x17Get Transaction By Hash\x1a%Get a single transaction by its hash.\x82\xd3\xe4\x93\x02':\x01*b\vtransaction\"\x15/getTransactionByHash\x12\xdf\x01\n" +
	"\x16GetTransactionsForTick\x122.qubic.v2.archive.pb.GetTransactionsForTickRequest\x1a3.qubic.v2.archive.pb.GetTransactionsForTickResponse\"\\\xbaG)\n" +
	"\fTransactions\x12\x19Get Transactions For Tick\x82\xd3\xe4\x93\x02*:\x01*b\ftransactions\"\x17/getTransactionsForTick\x12\xe5\x01\n" +
	"\x1aGetTransactionsForIdentity\x126.qubic.v2.archive.pb.GetTransactionsForIdentityRequest\x1a7.qubic.v2.archive.pb.GetTransactionsForIdentityResponse\"V\xbaG-\n" +
	"\fTransactions\x12\x1dGet Transactions For Identity\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/getTransactionsForIdentity\x12\xb3\x01\n" +
	"\vGetTickData\x12'.qubic.v2.archive.pb.GetTickDataRequest\x1a(.qubic.v2.archive.pb.GetTickDataResponse\"Q\xbaG7\n" +
	"\x05Ticks\x12\rGet Tick Data\x1a\x1fGet the tick data for one tick.\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/getTickData\x12\xcf\x01\n" +
	"\x19GetComputorsListsForEpoch\x124.qubic.v2.archive.pb.GetComputorListsForEpochRequest\x1a5.qubic.v2.archive.pb.GetComputorListsForEpochResponse\"E\xbaG\x1e\n" +
	"\aNetwork\x12\x13Get Epoch Computors\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/getComputorListsForEpoch\x12\xa5\x01\n" +
	"\x14GetLastProcessedTick\x12\x16.google.protobuf.Empty\x1a1.qubic.v2.archive.pb.GetLastProcessedTickResponse\"B\xbaG\"\n" +
	"\aArchive\x12\x17Get Last Processed Tick\x82\xd3\xe4\x93\x02\x17\x12\x15/getLastProcessedTick\x12\xd3\x01\n" +
	"\x19GetProcessedTickIntervals\x12\x16.google.protobuf.Empty\x1a6.qubic.v2.archive.pb.GetProcessedTickIntervalsResponse\"f\xbaG'\n" +
	"\aArchive\x12\x1cGet Processed Tick Intervals\x82\xd3\xe4\x93\x026b\x18processed_tick_intervals\x12\x1a/getProcessedTickIntervals\x12\xc7\x01\n" +
	"\tGetEvents\x12%.qubic.v2.archive.pb.GetEventsRequest\x1a&.qubic.v2.archive.pb.GetEventsResponse\"k\xbaGS\n" +
	"\rEvents (Beta)\x12\n" +
	"Get Events\x1a6Query event logs with optional filters. Beta endpoint.\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/getEvents\x12\xcd\x01\n" +
	"\tGetHealth\x12\x16.google.protobuf.Empty\x1a#.qubic.v2.archive.pb.HealthResponse\"\x82\x01\xbaGp\x12\n" +
	"Get Health\x1abHealth check. This is for internal use only and can change any time. Do not rely on this endpoint.\x82\xd3\xe4\x93\x02\t\x12\a/healthB\xfe\x03\xbaG\xce\x03\x12H\n" +
	"\x0fQubic Query API\x12.API for querying historical Qubic ledger data.2\x051.0.0\x1a \n" +
	"\x1ehttps://rpc.qubic.org/query/v1:*\n" +
	"\x05Ticks\x12!Query tick data from the archive.:8\n" +
	"\fTransactions\x12(Search and retrieve transaction history.:3\n" +
	"\aNetwork\x12(Network status and computor information.:>\n" +
	"\aArchive\x123Archive processing status and coverage information.:K\n" +
	"\rEvents (Beta)\x12:Query event logs from the Qubic blockchain. Beta endpoint.B8\n" +
	"\x06GitHub\x12.https://github.com/qubic/archive-query-serviceZ*github.com/qubic/archive-query-service/apib\x06proto3"

var file_query_services_proto_goTypes = []any{
	(*GetTransactionByHashRequest)(nil),        // 0: qubic.v2.archive.pb.GetTransactionByHashRequest
	(*GetTransactionsForTickRequest)(nil),      // 1: qubic.v2.archive.pb.GetTransactionsForTickRequest
	(*GetTransactionsForIdentityRequest)(nil),  // 2: qubic.v2.archive.pb.GetTransactionsForIdentityRequest
	(*GetTickDataRequest)(nil),                 // 3: qubic.v2.archive.pb.GetTickDataRequest
	(*GetComputorListsForEpochRequest)(nil),    // 4: qubic.v2.archive.pb.GetComputorListsForEpochRequest
	(*emptypb.Empty)(nil),                      // 5: google.protobuf.Empty
	(*GetEventsRequest)(nil),                   // 6: qubic.v2.archive.pb.GetEventsRequest
	(*GetTransactionByHashResponse)(nil),       // 7: qubic.v2.archive.pb.GetTransactionByHashResponse
	(*GetTransactionsForTickResponse)(nil),     // 8: qubic.v2.archive.pb.GetTransactionsForTickResponse
	(*GetTransactionsForIdentityResponse)(nil), // 9: qubic.v2.archive.pb.GetTransactionsForIdentityResponse
	(*GetTickDataResponse)(nil),                // 10: qubic.v2.archive.pb.GetTickDataResponse
	(*GetComputorListsForEpochResponse)(nil),   // 11: qubic.v2.archive.pb.GetComputorListsForEpochResponse
	(*GetLastProcessedTickResponse)(nil),       // 12: qubic.v2.archive.pb.GetLastProcessedTickResponse
	(*GetProcessedTickIntervalsResponse)(nil),  // 13: qubic.v2.archive.pb.GetProcessedTickIntervalsResponse
	(*GetEventsResponse)(nil),                  // 14: qubic.v2.archive.pb.GetEventsResponse
	(*HealthResponse)(nil),                     // 15: qubic.v2.archive.pb.HealthResponse
}
var file_query_services_proto_depIdxs = []int32{
	0,  // 0: qubic.v2.archive.pb.ArchiveQueryService.GetTransactionByHash:input_type -> qubic.v2.archive.pb.GetTransactionByHashRequest
	1,  // 1: qubic.v2.archive.pb.ArchiveQueryService.GetTransactionsForTick:input_type -> qubic.v2.archive.pb.GetTransactionsForTickRequest
	2,  // 2: qubic.v2.archive.pb.ArchiveQueryService.GetTransactionsForIdentity:input_type -> qubic.v2.archive.pb.GetTransactionsForIdentityRequest
	3,  // 3: qubic.v2.archive.pb.ArchiveQueryService.GetTickData:input_type -> qubic.v2.archive.pb.GetTickDataRequest
	4,  // 4: qubic.v2.archive.pb.ArchiveQueryService.GetComputorsListsForEpoch:input_type -> qubic.v2.archive.pb.GetComputorListsForEpochRequest
	5,  // 5: qubic.v2.archive.pb.ArchiveQueryService.GetLastProcessedTick:input_type -> google.protobuf.Empty
	5,  // 6: qubic.v2.archive.pb.ArchiveQueryService.GetProcessedTickIntervals:input_type -> google.protobuf.Empty
	6,  // 7: qubic.v2.archive.pb.ArchiveQueryService.GetEvents:input_type -> qubic.v2.archive.pb.GetEventsRequest
	5,  // 8: qubic.v2.archive.pb.ArchiveQueryService.GetHealth:input_type -> google.protobuf.Empty
	7,  // 9: qubic.v2.archive.pb.ArchiveQueryService.GetTransactionByHash:output_type -> qubic.v2.archive.pb.GetTransactionByHashResponse
	8,  // 10: qubic.v2.archive.pb.ArchiveQueryService.GetTransactionsForTick:output_type -> qubic.v2.archive.pb.GetTransactionsForTickResponse
	9,  // 11: qubic.v2.archive.pb.ArchiveQueryService.GetTransactionsForIdentity:output_type -> qubic.v2.archive.pb.GetTransactionsForIdentityResponse
	10, // 12: qubic.v2.archive.pb.ArchiveQueryService.GetTickData:output_type -> qubic.v2.archive.pb.GetTickDataResponse
	11, // 13: qubic.v2.archive.pb.ArchiveQueryService.GetComputorsListsForEpoch:output_type -> qubic.v2.archive.pb.GetComputorListsForEpochResponse
	12, // 14: qubic.v2.archive.pb.ArchiveQueryService.GetLastProcessedTick:output_type -> qubic.v2.archive.pb.GetLastProcessedTickResponse
	13, // 15: qubic.v2.archive.pb.ArchiveQueryService.GetProcessedTickIntervals:output_type -> qubic.v2.archive.pb.GetProcessedTickIntervalsResponse
	14, // 16: qubic.v2.archive.pb.ArchiveQueryService.GetEvents:output_type -> qubic.v2.archive.pb.GetEventsResponse
	15, // 17: qubic.v2.archive.pb.ArchiveQueryService.GetHealth:output_type -> qubic.v2.archive.pb.HealthResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_query_services_proto_init() }
func file_query_services_proto_init() {
	if File_query_services_proto != nil {
		return
	}
	file_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_services_proto_rawDesc), len(file_query_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_services_proto_goTypes,
		DependencyIndexes: file_query_services_proto_depIdxs,
	}.Build()
	File_query_services_proto = out.File
	file_query_services_proto_goTypes = nil
	file_query_services_proto_depIdxs = nil
}
