// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: query_services.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_query_services_proto protoreflect.FileDescriptor

const file_query_services_proto_rawDesc = "" +
	"\n" +
	"\x14query_services.proto\x12\x13qubic.v2.archive.pb\x1a\x0emessages.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto2\xab\x05\n" +
	"\x13ArchiveQueryService\x12\xaa\x01\n" +
	"\x14GetTransactionByHash\x120.qubic.v2.archive.pb.GetTransactionByHashRequest\x1a1.qubic.v2.archive.pb.GetTransactionByHashResponse\"-\x82\xd3\xe4\x93\x02':\x01*b\vtransaction\"\x15/getTransactionByHash\x12\xb3\x01\n" +
	"\x16GetTransactionsForTick\x122.qubic.v2.archive.pb.GetTransactionsForTickRequest\x1a3.qubic.v2.archive.pb.GetTransactionsForTickResponse\"0\x82\xd3\xe4\x93\x02*:\x01*b\ftransactions\"\x17/getTransactionsForTick\x12\xb5\x01\n" +
	"\x1aGetTransactionsForIdentity\x126.qubic.v2.archive.pb.GetTransactionsForIdentityRequest\x1a7.qubic.v2.archive.pb.GetTransactionsForIdentityResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/getTransactionsForIdentity\x12y\n" +
	"\vGetTickData\x12'.qubic.v2.archive.pb.GetTickDataRequest\x1a(.qubic.v2.archive.pb.GetTickDataResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/getTickDataB,Z*github.com/qubic/archive-query-service/apib\x06proto3"

var file_query_services_proto_goTypes = []any{
	(*GetTransactionByHashRequest)(nil),        // 0: qubic.v2.archive.pb.GetTransactionByHashRequest
	(*GetTransactionsForTickRequest)(nil),      // 1: qubic.v2.archive.pb.GetTransactionsForTickRequest
	(*GetTransactionsForIdentityRequest)(nil),  // 2: qubic.v2.archive.pb.GetTransactionsForIdentityRequest
	(*GetTickDataRequest)(nil),                 // 3: qubic.v2.archive.pb.GetTickDataRequest
	(*GetTransactionByHashResponse)(nil),       // 4: qubic.v2.archive.pb.GetTransactionByHashResponse
	(*GetTransactionsForTickResponse)(nil),     // 5: qubic.v2.archive.pb.GetTransactionsForTickResponse
	(*GetTransactionsForIdentityResponse)(nil), // 6: qubic.v2.archive.pb.GetTransactionsForIdentityResponse
	(*GetTickDataResponse)(nil),                // 7: qubic.v2.archive.pb.GetTickDataResponse
}
var file_query_services_proto_depIdxs = []int32{
	0, // 0: qubic.v2.archive.pb.ArchiveQueryService.GetTransactionByHash:input_type -> qubic.v2.archive.pb.GetTransactionByHashRequest
	1, // 1: qubic.v2.archive.pb.ArchiveQueryService.GetTransactionsForTick:input_type -> qubic.v2.archive.pb.GetTransactionsForTickRequest
	2, // 2: qubic.v2.archive.pb.ArchiveQueryService.GetTransactionsForIdentity:input_type -> qubic.v2.archive.pb.GetTransactionsForIdentityRequest
	3, // 3: qubic.v2.archive.pb.ArchiveQueryService.GetTickData:input_type -> qubic.v2.archive.pb.GetTickDataRequest
	4, // 4: qubic.v2.archive.pb.ArchiveQueryService.GetTransactionByHash:output_type -> qubic.v2.archive.pb.GetTransactionByHashResponse
	5, // 5: qubic.v2.archive.pb.ArchiveQueryService.GetTransactionsForTick:output_type -> qubic.v2.archive.pb.GetTransactionsForTickResponse
	6, // 6: qubic.v2.archive.pb.ArchiveQueryService.GetTransactionsForIdentity:output_type -> qubic.v2.archive.pb.GetTransactionsForIdentityResponse
	7, // 7: qubic.v2.archive.pb.ArchiveQueryService.GetTickData:output_type -> qubic.v2.archive.pb.GetTickDataResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_query_services_proto_init() }
func file_query_services_proto_init() {
	if File_query_services_proto != nil {
		return
	}
	file_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_services_proto_rawDesc), len(file_query_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_services_proto_goTypes,
		DependencyIndexes: file_query_services_proto_depIdxs,
	}.Build()
	File_query_services_proto = out.File
	file_query_services_proto_goTypes = nil
	file_query_services_proto_depIdxs = nil
}
