// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: query_services.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArchiveQueryService_GetTransactionByHash_FullMethodName       = "/qubic.v2.archive.pb.ArchiveQueryService/GetTransactionByHash"
	ArchiveQueryService_GetTransactionsForTick_FullMethodName     = "/qubic.v2.archive.pb.ArchiveQueryService/GetTransactionsForTick"
	ArchiveQueryService_GetTransactionsForIdentity_FullMethodName = "/qubic.v2.archive.pb.ArchiveQueryService/GetTransactionsForIdentity"
	ArchiveQueryService_GetTickData_FullMethodName                = "/qubic.v2.archive.pb.ArchiveQueryService/GetTickData"
	ArchiveQueryService_GetComputorsListsForEpoch_FullMethodName  = "/qubic.v2.archive.pb.ArchiveQueryService/GetComputorsListsForEpoch"
	ArchiveQueryService_GetLastProcessedTick_FullMethodName       = "/qubic.v2.archive.pb.ArchiveQueryService/GetLastProcessedTick"
	ArchiveQueryService_GetProcessedTickIntervals_FullMethodName  = "/qubic.v2.archive.pb.ArchiveQueryService/GetProcessedTickIntervals"
	ArchiveQueryService_GetEvents_FullMethodName                  = "/qubic.v2.archive.pb.ArchiveQueryService/GetEvents"
	ArchiveQueryService_GetHealth_FullMethodName                  = "/qubic.v2.archive.pb.ArchiveQueryService/GetHealth"
)

// ArchiveQueryServiceClient is the client API for ArchiveQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Qubic Query API
type ArchiveQueryServiceClient interface {
	GetTransactionByHash(ctx context.Context, in *GetTransactionByHashRequest, opts ...grpc.CallOption) (*GetTransactionByHashResponse, error)
	// Get the transactions that are in included in one tick.
	//
	// ###  Request structure
	//
	// | Name       | Type               | Necessity | Description                                     |
	// |------------|--------------------|-----------|-------------------------------------------------|
	// | identity   | string             | required  | 60 characters uppercase identity.               |
	// | filters    | map<string,string> | optional  | Filters that restrict results to single value.  |
	// | ranges     | map<string,Range>  | optional  | Filters that restrict results to a value range. |
	//
	// ### Filters
	//
	// Filters restrict the results by single values.
	//
	// #### Allowed properties
	//
	// | Name        |  Type   | Format                 | Description                                                        |
	// |-------------|---------|------------------------|--------------------------------------------------------------------|
	// | source      | string  | 60 character identity  | Only find transactions that were sent from the specified identities. |
	// | destination | string  | 60 character identity  | Only find transactions that were sent to the specified identities.   |
	// | amount      | string  | Numeric                | Only find transactions with the specified amount.                  |
	// | inputType   | string  | Numeric                | Only find transactions with the specified input type.              |
	//
	// ### Ranges
	//
	// Ranges restrict the results by a range of values. On range per property is supported.
	//
	// #### Allowed properties
	//
	// | Name       | Type   | Format                                   | Description                                 |
	// |------------|--------|------------------------------------------|---------------------------------------------|
	// | amount     | string | Numeric                                  | Only find transactions in amount range.     |
	// | inputType  | string | Numeric                                  | Only find transactions in input type range. |
	//
	// #### Range definition
	//
	// A range with size of 0 or 1 is not allowed.
	//
	// | Name      | Type   | Necessity | Description                               |
	// |-----------|--------|-----------|-------------------------------------------|
	// | field | string | required  | Name of the field you wish to search for. |
	// | gt        | string | optional  | Greater than.                             |
	// | gte       | string | optional  | Greater than or equal to.                 |
	// | lt        | string | optional  | Less than.                                |
	// | lte       | string | optional  | Less than or equal to.                    |
	//
	// Only one lower bound and one upper bound can be specified.
	//
	// For examples how to use filters and ranges see the GetTransactionsForIdentity endpoint documentation.
	GetTransactionsForTick(ctx context.Context, in *GetTransactionsForTickRequest, opts ...grpc.CallOption) (*GetTransactionsForTickResponse, error)
	// Get the transactions for one identity sorted by tick number descending.
	//
	// ###  Request structure
	//
	// | Name       | Type               | Necessity | Description                                                                    |
	// |------------|--------------------|-----------|--------------------------------------------------------------------------------|
	// | identity   | string             | required  | 60 characters uppercase identity.                                              |
	// | filters    | map<string,string> | optional  | Filters that restrict results to single value.                                 |
	// | ranges     | map<string,Range>  | optional  | Filters that restrict results to a value range.                                |
	// | pagination | Pagination         | optional  | Allows to specify the first record and the number of records to be retrieved.  |
	//
	// Without filters and ranges all transactions from and to that identity ordered by tick number descending are returned.
	//
	// ### Filters
	//
	// Filters restrict the results by single values.
	//
	// #### Allowed properties
	//
	// | Name        |  Type   | Format                 | Description                                                        |
	// |-------------|---------|------------------------|--------------------------------------------------------------------|
	// | source      | string | 60 character identity, up to 5, comma separated. | Only find transactions that were sent from the specified identities. |
	// | source-exclude | string | 60 character identity, up to 5, comma separated.  | Only find transactions that were not sent from the specified identities. |
	// | destination | string | 60 character identity, up to 5, comma separated.  | Only find transactions that were sent to the specified identities.   |
	// | destination-exclude | string | 60 character identity, up to 5, comma separated.  | Only find transactions that were not sent to the specified identities.   |
	// | amount      | string | Numeric                | Only find transactions with the specified amount.                  |
	// | inputType   | string | Numeric                | Only find transactions with the specified input type.              |
	// | tickNumber  | string | Numeric                | Only find transactions with the specified tick number.             |
	//
	// source` and `source-exclude` are mutually exclusive.
	// destination` and `destination-exclude` are mutually exclusive.
	//
	// #### Examples
	//
	// ```
	// "source": "IIJHZSNPDRYYXCQBWNGKBSWYYDCARTYPOBXGOXZEVEZMMWYHPBVXZLJARRCB",
	// "destination": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"
	// "amount": "1000000"
	// "inputType": "0"
	// ```
	//
	// ### Ranges
	//
	// Ranges restrict the results by a range of values. On range per property is supported.
	//
	// #### Allowed properties
	//
	// | Name       | Type   | Format                                   | Description                                 |
	// |------------|--------|------------------------------------------|---------------------------------------------|
	// | amount     | string | Numeric                                  | Only find transactions in amount range.     |
	// | tickNumber | string | Numeric                                  | Only find transactions in tick range.       |
	// | inputType  | string | Numeric                                  | Only find transactions in input type range. |
	// | timestamp  | string | Numeric (Unix Timestamp in milliseconds) | Only find transactions in time range.       |
	//
	// #### Range definition
	//
	// A range with size of 0 or 1 is not allowed.
	//
	// | Name      | Type   | Necessity | Description                               |
	// |-----------|--------|-----------|-------------------------------------------|
	// | field | string | required  | Name of the field you wish to search for. |
	// | gt        | string | optional  | Greater than.                             |
	// | gte       | string | optional  | Greater than or equal to.                 |
	// | lt        | string | optional  | Less than.                                |
	// | lte       | string | optional  | Less than or equal to.                    |
	//
	// Only one lower bound and one upper bound can be specified.
	//
	// #### Examples
	//
	// ```
	// "amount": { "gt": "1000000" }
	// "tickNumber": { "gte": "25563000", "lte": "28300000" }
	// "inputType": { "gt": "0" }
	// "timestamp": { "lt": "1757376000000" }
	// ```
	//
	// ### Pagination
	//
	// | Name   | Type   | Necessity | Description                                                                                         |
	// |--------|--------|-----------|-----------------------------------------------------------------------------------------------------|
	// | offset | uint32 | optional  | The offset of the first record to return. Defaults to zero (first record). Maximum offset is 10000. |
	// | size   | uint32 | optional  | Defaults to 10. Maximum size is 1000. Zero value is ignored (uses default). |
	GetTransactionsForIdentity(ctx context.Context, in *GetTransactionsForIdentityRequest, opts ...grpc.CallOption) (*GetTransactionsForIdentityResponse, error)
	GetTickData(ctx context.Context, in *GetTickDataRequest, opts ...grpc.CallOption) (*GetTickDataResponse, error)
	// Get the list(s) of computors for one epoch. These are the computors (IDs signed by the arbitrator) that
	// are allowed to make quorum decisions. It is possible that this list changes within the epoch in case of
	// arbitrator intervention.
	GetComputorsListsForEpoch(ctx context.Context, in *GetComputorListsForEpochRequest, opts ...grpc.CallOption) (*GetComputorListsForEpochResponse, error)
	// Get the last processed tick and other processing information from the archive.
	// All data queried from the archive is only fully processed up to this tick.
	// Before calling the service you should check the last processed tick to be sure to get
	// valid data and do not request data for future ticks that are not processed yet. You can use
	// the epoch and initial tick information in the response to switch to a new interval.
	GetLastProcessedTick(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetLastProcessedTickResponse, error)
	// Get the tick intervals that are available in the archive. A new tick interval is typically
	// created on epoch change or network restart within the epoch. Use this endpoint to skip the
	// tick numbers that are not part of the intervals. This endpoint is only necessary for users
	// that need to process all available ticks. For most users it is enough to switch to a new
	// interval by using the `get last processed tick` endpoint.
	GetProcessedTickIntervals(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetProcessedTickIntervalsResponse, error)
	// Query event logs with optional filters. Beta endpoint.
	//
	// ###  Request structure
	//
	// | Name       | Type               | Necessity | Description                                                    |
	// |------------|--------------------|-----------|----------------------------------------------------------------|
	// | filters    | map<string,string> | optional  | Filters that restrict results to single value.                 |
	// | pagination | Pagination         | optional  | Allows to specify the first record and number of records.      |
	//
	// ### Filters
	//
	// | Name            |  Type   | Format   | Description                                             |
	// |-----------------|---------|----------|---------------------------------------------------------|
	// | transactionHash | string  | Hash     | Only find events for the specified transaction hash.    |
	// | tickNumber      | string  | Numeric  | Only find events for the specified tick number.         |
	// | eventType       | string  | Numeric  | Only find events with the specified type (0,1,2,3,8,13).|
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
	GetHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type archiveQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArchiveQueryServiceClient(cc grpc.ClientConnInterface) ArchiveQueryServiceClient {
	return &archiveQueryServiceClient{cc}
}

func (c *archiveQueryServiceClient) GetTransactionByHash(ctx context.Context, in *GetTransactionByHashRequest, opts ...grpc.CallOption) (*GetTransactionByHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionByHashResponse)
	err := c.cc.Invoke(ctx, ArchiveQueryService_GetTransactionByHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *archiveQueryServiceClient) GetTransactionsForTick(ctx context.Context, in *GetTransactionsForTickRequest, opts ...grpc.CallOption) (*GetTransactionsForTickResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionsForTickResponse)
	err := c.cc.Invoke(ctx, ArchiveQueryService_GetTransactionsForTick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *archiveQueryServiceClient) GetTransactionsForIdentity(ctx context.Context, in *GetTransactionsForIdentityRequest, opts ...grpc.CallOption) (*GetTransactionsForIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionsForIdentityResponse)
	err := c.cc.Invoke(ctx, ArchiveQueryService_GetTransactionsForIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *archiveQueryServiceClient) GetTickData(ctx context.Context, in *GetTickDataRequest, opts ...grpc.CallOption) (*GetTickDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTickDataResponse)
	err := c.cc.Invoke(ctx, ArchiveQueryService_GetTickData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *archiveQueryServiceClient) GetComputorsListsForEpoch(ctx context.Context, in *GetComputorListsForEpochRequest, opts ...grpc.CallOption) (*GetComputorListsForEpochResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetComputorListsForEpochResponse)
	err := c.cc.Invoke(ctx, ArchiveQueryService_GetComputorsListsForEpoch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *archiveQueryServiceClient) GetLastProcessedTick(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetLastProcessedTickResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLastProcessedTickResponse)
	err := c.cc.Invoke(ctx, ArchiveQueryService_GetLastProcessedTick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *archiveQueryServiceClient) GetProcessedTickIntervals(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetProcessedTickIntervalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProcessedTickIntervalsResponse)
	err := c.cc.Invoke(ctx, ArchiveQueryService_GetProcessedTickIntervals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *archiveQueryServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, ArchiveQueryService_GetEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *archiveQueryServiceClient) GetHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ArchiveQueryService_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArchiveQueryServiceServer is the server API for ArchiveQueryService service.
// All implementations must embed UnimplementedArchiveQueryServiceServer
// for forward compatibility.
//
// Qubic Query API
type ArchiveQueryServiceServer interface {
	GetTransactionByHash(context.Context, *GetTransactionByHashRequest) (*GetTransactionByHashResponse, error)
	// Get the transactions that are in included in one tick.
	//
	// ###  Request structure
	//
	// | Name       | Type               | Necessity | Description                                     |
	// |------------|--------------------|-----------|-------------------------------------------------|
	// | identity   | string             | required  | 60 characters uppercase identity.               |
	// | filters    | map<string,string> | optional  | Filters that restrict results to single value.  |
	// | ranges     | map<string,Range>  | optional  | Filters that restrict results to a value range. |
	//
	// ### Filters
	//
	// Filters restrict the results by single values.
	//
	// #### Allowed properties
	//
	// | Name        |  Type   | Format                 | Description                                                        |
	// |-------------|---------|------------------------|--------------------------------------------------------------------|
	// | source      | string  | 60 character identity  | Only find transactions that were sent from the specified identities. |
	// | destination | string  | 60 character identity  | Only find transactions that were sent to the specified identities.   |
	// | amount      | string  | Numeric                | Only find transactions with the specified amount.                  |
	// | inputType   | string  | Numeric                | Only find transactions with the specified input type.              |
	//
	// ### Ranges
	//
	// Ranges restrict the results by a range of values. On range per property is supported.
	//
	// #### Allowed properties
	//
	// | Name       | Type   | Format                                   | Description                                 |
	// |------------|--------|------------------------------------------|---------------------------------------------|
	// | amount     | string | Numeric                                  | Only find transactions in amount range.     |
	// | inputType  | string | Numeric                                  | Only find transactions in input type range. |
	//
	// #### Range definition
	//
	// A range with size of 0 or 1 is not allowed.
	//
	// | Name      | Type   | Necessity | Description                               |
	// |-----------|--------|-----------|-------------------------------------------|
	// | field | string | required  | Name of the field you wish to search for. |
	// | gt        | string | optional  | Greater than.                             |
	// | gte       | string | optional  | Greater than or equal to.                 |
	// | lt        | string | optional  | Less than.                                |
	// | lte       | string | optional  | Less than or equal to.                    |
	//
	// Only one lower bound and one upper bound can be specified.
	//
	// For examples how to use filters and ranges see the GetTransactionsForIdentity endpoint documentation.
	GetTransactionsForTick(context.Context, *GetTransactionsForTickRequest) (*GetTransactionsForTickResponse, error)
	// Get the transactions for one identity sorted by tick number descending.
	//
	// ###  Request structure
	//
	// | Name       | Type               | Necessity | Description                                                                    |
	// |------------|--------------------|-----------|--------------------------------------------------------------------------------|
	// | identity   | string             | required  | 60 characters uppercase identity.                                              |
	// | filters    | map<string,string> | optional  | Filters that restrict results to single value.                                 |
	// | ranges     | map<string,Range>  | optional  | Filters that restrict results to a value range.                                |
	// | pagination | Pagination         | optional  | Allows to specify the first record and the number of records to be retrieved.  |
	//
	// Without filters and ranges all transactions from and to that identity ordered by tick number descending are returned.
	//
	// ### Filters
	//
	// Filters restrict the results by single values.
	//
	// #### Allowed properties
	//
	// | Name        |  Type   | Format                 | Description                                                        |
	// |-------------|---------|------------------------|--------------------------------------------------------------------|
	// | source      | string | 60 character identity, up to 5, comma separated. | Only find transactions that were sent from the specified identities. |
	// | source-exclude | string | 60 character identity, up to 5, comma separated.  | Only find transactions that were not sent from the specified identities. |
	// | destination | string | 60 character identity, up to 5, comma separated.  | Only find transactions that were sent to the specified identities.   |
	// | destination-exclude | string | 60 character identity, up to 5, comma separated.  | Only find transactions that were not sent to the specified identities.   |
	// | amount      | string | Numeric                | Only find transactions with the specified amount.                  |
	// | inputType   | string | Numeric                | Only find transactions with the specified input type.              |
	// | tickNumber  | string | Numeric                | Only find transactions with the specified tick number.             |
	//
	// source` and `source-exclude` are mutually exclusive.
	// destination` and `destination-exclude` are mutually exclusive.
	//
	// #### Examples
	//
	// ```
	// "source": "IIJHZSNPDRYYXCQBWNGKBSWYYDCARTYPOBXGOXZEVEZMMWYHPBVXZLJARRCB",
	// "destination": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"
	// "amount": "1000000"
	// "inputType": "0"
	// ```
	//
	// ### Ranges
	//
	// Ranges restrict the results by a range of values. On range per property is supported.
	//
	// #### Allowed properties
	//
	// | Name       | Type   | Format                                   | Description                                 |
	// |------------|--------|------------------------------------------|---------------------------------------------|
	// | amount     | string | Numeric                                  | Only find transactions in amount range.     |
	// | tickNumber | string | Numeric                                  | Only find transactions in tick range.       |
	// | inputType  | string | Numeric                                  | Only find transactions in input type range. |
	// | timestamp  | string | Numeric (Unix Timestamp in milliseconds) | Only find transactions in time range.       |
	//
	// #### Range definition
	//
	// A range with size of 0 or 1 is not allowed.
	//
	// | Name      | Type   | Necessity | Description                               |
	// |-----------|--------|-----------|-------------------------------------------|
	// | field | string | required  | Name of the field you wish to search for. |
	// | gt        | string | optional  | Greater than.                             |
	// | gte       | string | optional  | Greater than or equal to.                 |
	// | lt        | string | optional  | Less than.                                |
	// | lte       | string | optional  | Less than or equal to.                    |
	//
	// Only one lower bound and one upper bound can be specified.
	//
	// #### Examples
	//
	// ```
	// "amount": { "gt": "1000000" }
	// "tickNumber": { "gte": "25563000", "lte": "28300000" }
	// "inputType": { "gt": "0" }
	// "timestamp": { "lt": "1757376000000" }
	// ```
	//
	// ### Pagination
	//
	// | Name   | Type   | Necessity | Description                                                                                         |
	// |--------|--------|-----------|-----------------------------------------------------------------------------------------------------|
	// | offset | uint32 | optional  | The offset of the first record to return. Defaults to zero (first record). Maximum offset is 10000. |
	// | size   | uint32 | optional  | Defaults to 10. Maximum size is 1000. Zero value is ignored (uses default). |
	GetTransactionsForIdentity(context.Context, *GetTransactionsForIdentityRequest) (*GetTransactionsForIdentityResponse, error)
	GetTickData(context.Context, *GetTickDataRequest) (*GetTickDataResponse, error)
	// Get the list(s) of computors for one epoch. These are the computors (IDs signed by the arbitrator) that
	// are allowed to make quorum decisions. It is possible that this list changes within the epoch in case of
	// arbitrator intervention.
	GetComputorsListsForEpoch(context.Context, *GetComputorListsForEpochRequest) (*GetComputorListsForEpochResponse, error)
	// Get the last processed tick and other processing information from the archive.
	// All data queried from the archive is only fully processed up to this tick.
	// Before calling the service you should check the last processed tick to be sure to get
	// valid data and do not request data for future ticks that are not processed yet. You can use
	// the epoch and initial tick information in the response to switch to a new interval.
	GetLastProcessedTick(context.Context, *emptypb.Empty) (*GetLastProcessedTickResponse, error)
	// Get the tick intervals that are available in the archive. A new tick interval is typically
	// created on epoch change or network restart within the epoch. Use this endpoint to skip the
	// tick numbers that are not part of the intervals. This endpoint is only necessary for users
	// that need to process all available ticks. For most users it is enough to switch to a new
	// interval by using the `get last processed tick` endpoint.
	GetProcessedTickIntervals(context.Context, *emptypb.Empty) (*GetProcessedTickIntervalsResponse, error)
	// Query event logs with optional filters. Beta endpoint.
	//
	// ###  Request structure
	//
	// | Name       | Type               | Necessity | Description                                                    |
	// |------------|--------------------|-----------|----------------------------------------------------------------|
	// | filters    | map<string,string> | optional  | Filters that restrict results to single value.                 |
	// | pagination | Pagination         | optional  | Allows to specify the first record and number of records.      |
	//
	// ### Filters
	//
	// | Name            |  Type   | Format   | Description                                             |
	// |-----------------|---------|----------|---------------------------------------------------------|
	// | transactionHash | string  | Hash     | Only find events for the specified transaction hash.    |
	// | tickNumber      | string  | Numeric  | Only find events for the specified tick number.         |
	// | eventType       | string  | Numeric  | Only find events with the specified type (0,1,2,3,8,13).|
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
	GetHealth(context.Context, *emptypb.Empty) (*HealthResponse, error)
	mustEmbedUnimplementedArchiveQueryServiceServer()
}

// UnimplementedArchiveQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArchiveQueryServiceServer struct{}

func (UnimplementedArchiveQueryServiceServer) GetTransactionByHash(context.Context, *GetTransactionByHashRequest) (*GetTransactionByHashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactionByHash not implemented")
}
func (UnimplementedArchiveQueryServiceServer) GetTransactionsForTick(context.Context, *GetTransactionsForTickRequest) (*GetTransactionsForTickResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactionsForTick not implemented")
}
func (UnimplementedArchiveQueryServiceServer) GetTransactionsForIdentity(context.Context, *GetTransactionsForIdentityRequest) (*GetTransactionsForIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactionsForIdentity not implemented")
}
func (UnimplementedArchiveQueryServiceServer) GetTickData(context.Context, *GetTickDataRequest) (*GetTickDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTickData not implemented")
}
func (UnimplementedArchiveQueryServiceServer) GetComputorsListsForEpoch(context.Context, *GetComputorListsForEpochRequest) (*GetComputorListsForEpochResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetComputorsListsForEpoch not implemented")
}
func (UnimplementedArchiveQueryServiceServer) GetLastProcessedTick(context.Context, *emptypb.Empty) (*GetLastProcessedTickResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastProcessedTick not implemented")
}
func (UnimplementedArchiveQueryServiceServer) GetProcessedTickIntervals(context.Context, *emptypb.Empty) (*GetProcessedTickIntervalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProcessedTickIntervals not implemented")
}
func (UnimplementedArchiveQueryServiceServer) GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedArchiveQueryServiceServer) GetHealth(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedArchiveQueryServiceServer) mustEmbedUnimplementedArchiveQueryServiceServer() {}
func (UnimplementedArchiveQueryServiceServer) testEmbeddedByValue()                             {}

// UnsafeArchiveQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArchiveQueryServiceServer will
// result in compilation errors.
type UnsafeArchiveQueryServiceServer interface {
	mustEmbedUnimplementedArchiveQueryServiceServer()
}

func RegisterArchiveQueryServiceServer(s grpc.ServiceRegistrar, srv ArchiveQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedArchiveQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArchiveQueryService_ServiceDesc, srv)
}

func _ArchiveQueryService_GetTransactionByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveQueryServiceServer).GetTransactionByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveQueryService_GetTransactionByHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveQueryServiceServer).GetTransactionByHash(ctx, req.(*GetTransactionByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArchiveQueryService_GetTransactionsForTick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionsForTickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveQueryServiceServer).GetTransactionsForTick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveQueryService_GetTransactionsForTick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveQueryServiceServer).GetTransactionsForTick(ctx, req.(*GetTransactionsForTickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArchiveQueryService_GetTransactionsForIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionsForIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveQueryServiceServer).GetTransactionsForIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveQueryService_GetTransactionsForIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveQueryServiceServer).GetTransactionsForIdentity(ctx, req.(*GetTransactionsForIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArchiveQueryService_GetTickData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTickDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveQueryServiceServer).GetTickData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveQueryService_GetTickData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveQueryServiceServer).GetTickData(ctx, req.(*GetTickDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArchiveQueryService_GetComputorsListsForEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComputorListsForEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveQueryServiceServer).GetComputorsListsForEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveQueryService_GetComputorsListsForEpoch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveQueryServiceServer).GetComputorsListsForEpoch(ctx, req.(*GetComputorListsForEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArchiveQueryService_GetLastProcessedTick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveQueryServiceServer).GetLastProcessedTick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveQueryService_GetLastProcessedTick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveQueryServiceServer).GetLastProcessedTick(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArchiveQueryService_GetProcessedTickIntervals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveQueryServiceServer).GetProcessedTickIntervals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveQueryService_GetProcessedTickIntervals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveQueryServiceServer).GetProcessedTickIntervals(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArchiveQueryService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveQueryServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveQueryService_GetEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveQueryServiceServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArchiveQueryService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveQueryServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveQueryService_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveQueryServiceServer).GetHealth(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ArchiveQueryService_ServiceDesc is the grpc.ServiceDesc for ArchiveQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArchiveQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qubic.v2.archive.pb.ArchiveQueryService",
	HandlerType: (*ArchiveQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTransactionByHash",
			Handler:    _ArchiveQueryService_GetTransactionByHash_Handler,
		},
		{
			MethodName: "GetTransactionsForTick",
			Handler:    _ArchiveQueryService_GetTransactionsForTick_Handler,
		},
		{
			MethodName: "GetTransactionsForIdentity",
			Handler:    _ArchiveQueryService_GetTransactionsForIdentity_Handler,
		},
		{
			MethodName: "GetTickData",
			Handler:    _ArchiveQueryService_GetTickData_Handler,
		},
		{
			MethodName: "GetComputorsListsForEpoch",
			Handler:    _ArchiveQueryService_GetComputorsListsForEpoch_Handler,
		},
		{
			MethodName: "GetLastProcessedTick",
			Handler:    _ArchiveQueryService_GetLastProcessedTick_Handler,
		},
		{
			MethodName: "GetProcessedTickIntervals",
			Handler:    _ArchiveQueryService_GetProcessedTickIntervals_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _ArchiveQueryService_GetEvents_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _ArchiveQueryService_GetHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "query_services.proto",
}
