name: Deploy v2 prod images to GHCR

on:
  push:
    tags:
      - 'v2/v*.*.*'

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract module and version from tag
        id: extract
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          MODULE_NAME=$(echo "$TAG" | cut -d/ -f1)
          VERSION=$(echo "$TAG" | cut -d/ -f2)
          echo "module=$MODULE_NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./v2
          file: ./v2/Dockerfile
          push: true
          tags: ghcr.io/qubic/archive-query-service-v2:${{ steps.extract.outputs.version }}